# Generated by Django 3.2.9 on 2021-12-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_core', '0002_auto_20211217_1029'),
        ('profiles', '0004_alter_usernet_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_users', to='bank_core.bank'),
        ),
    ]
