# Generated by Django 3.2.9 on 2021-12-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=120, unique=True)),
                ('year_of_foundation', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='bank_core.bank'),
        ),
    ]
