# Generated by Django 3.2.9 on 2021-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_core', '0002_auto_20211217_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
